name = "linuxcore-dev"
compatibility_date = "2026-04-09"
compatibility_flags = ["nodejs_compat"]
[vars]
PRINTIFY_SHOP_ID = "27112844"
CONTACT_TO_EMAIL = "airbrushden@gmail.com"
CONTACT_FROM = "contact@linuxcore.dev"

[assets]
directory = "dist/client"
binding = "ASSETS"
